version: '3'

services:
  backend:
    build:
      context: ./demo-server
    restart: always
    ports:
      - "4000:4000"
    networks:
      - frontend
      - backend
    environment:
      - MONGODB_URI=mongodb://db:27017/courses
      - PORT=4000
    depends_on:
      - db


  db:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
networks:
  backend: {}
  frontend: {}
volumes:
  mongo-data: {}
